function(ADD_WIDGET_LIBRARY WIDGET_CLASS_NAME WIDGET_FILE_NAME)
    add_library("${WIDGET_CLASS_NAME}" STATIC "${WIDGET_FILE_NAME}.cpp" "${WIDGET_FILE_NAME}.ui" "${WIDGETS_INCLUDE_DIR}/${WIDGET_FILE_NAME}.h")
    target_include_directories("${WIDGET_CLASS_NAME}" PRIVATE "${WIDGETS_INCLUDE_DIR}")
endfunction(ADD_WIDGET_LIBRARY)
